const CART_LIST_SUCCESS = "CART_LIST_SUCCESS";
const CART_LIST_REQUEST = "CART_LIST_REQUEST";
const CART_LIST_FAIL = "CART_LIST_FAIL";
const ITEM_SAVE_REQUEST = "ITEM_SAVE_REQUEST";
const ITEM_SAVE_SUCCESS = "ITEM_SAVE_SUCCESS";
const ITEM_SAVE_FAIL = "ITEM_SAVE_FAIL";
const ITEM_DELETE_FAIL = "ITEM_DELETE_FAIL";
const ITEM_DELETE_REQUEST = "ITEM_DELETE_REQUEST";
const ITEM_DELETE_SUCCESS = "ITEM_DELETE_SUCCESS";

export {CART_LIST_FAIL,
    CART_LIST_SUCCESS,
    CART_LIST_REQUEST,
    ITEM_DELETE_REQUEST,
    ITEM_DELETE_SUCCESS,
    ITEM_DELETE_FAIL,
    ITEM_SAVE_REQUEST,
    ITEM_SAVE_SUCCESS,
    ITEM_SAVE_FAIL};