const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";
const ORDERS_REQUEST = "ORDERS_REQUEST";
const ORDERS_SUCCESS = "ORDERS_SUCCESS";
const ORDERS_FAIL = "ORDERS_FAIL";
const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";
const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST";
const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
const CANCEL_ORDER_FAIL = "CANCEL_ORDER_FAIL";
const CHANGE_STATUS_REQUEST = "CHANGE_STATUS_REQUEST";
const CHANGE_STATUS_SUCCESS = "CHANGE_STATUS_SUCCESS";
const CHANGE_STATUS_FAIL = "CHANGE_STATUS_FAIL";

export { 
    ORDER_LIST_REQUEST,
    ORDER_LIST_SUCCESS,
    ORDER_LIST_FAIL,
    ORDERS_REQUEST,
    ORDERS_SUCCESS,
    ORDERS_FAIL,
    PLACE_ORDER_FAIL,
    PLACE_ORDER_SUCCESS,
    PLACE_ORDER_REQUEST,
    CANCEL_ORDER_FAIL,
    CANCEL_ORDER_SUCCESS,
    CANCEL_ORDER_REQUEST,
    CHANGE_STATUS_FAIL,
    CHANGE_STATUS_SUCCESS,
    CHANGE_STATUS_REQUEST
};